name: Create RIO build
description: 'creates a build on the platform and saves build details in file'
runs:
  using: composite
  steps:
    - id: create
      run: python .github/scripts/create_build.py .github/app_config/build.yaml
      shell: bash